export const KEYWORDS: Record<string, number> = {
  website: 70,
  websites: 70,
  url: 70,
  urls: 70,
  link: 70,
  links: 70,
  homepage: 70,
  site: 70,
  web: 70,
  social: 71,
  socials: 71,
  'socials?': 71,
  'socials.': 71,
  'socials!': 71,
  socialmedia: 71,
  'social-media': 71,
  'social media': 71,
  handle: 78,
  handles: 78,
  mainhandle: 78,
  username: 78,
  account: 78,
  media: 71,
  snapchat: 72,
  linkedin: 73,
  facebook: 74,
  fb: 74,
  instagram: 75,
  insta: 75,
  ig: 75,
  tiktok: 76,
  tok: 76,
  "socials,": 71,
  x: 77,
  twitter: 77,
  location: 22,
  address: 22,
  where: 22,
  ceo: 21,
  leader: 21,
  dagligleder: 22,
  "daglig leder": 22,
  managingdirector: 22,
  "managing director": 22,
  oystein: 22,
    oysteingn: 22,

  oestein: 22,
  øystein: 22,
  øysteingn: 22,
  øysteign: 22,

  øyestein: 22,
  frustol: 22,
  frustøl: 22,
  frøstøl: 22,
  frøestøl: 22,
  frostøl: 22,
  frusol: 22,
  furestol: 22,
  contact: 20,
  support: 34,
  helpdesk: 34,
  customer: 34,
  service: 34,
  phone: 20,
  mobile: 34,
  telephone: 34,
  tel: 34,
  call: 34,
  email: 20,
  mail: 34,
  message: 34,
  dm: 71,
  reach: 34,
  reachout: 34,
  founder: 21,
  flavour: 10,
  flavor: 10,
  flavors: 10,
  flavours: 10,
  products: 10,
  product: 10,
  bottle: 25,
  bottles: 25,
  backpack: 22,
  backpacks: 22,
  thermos: 25,
  thermobottle: 25,
  lunchbox: 27,
  lunchboxes: 27,
  what: 1,
  sustainable: 4,
  eco: 4,
  green: 4,
  foundation: 5,
  carbon: 6,
  packaging: 7,
  can: 7,
  plastic: 8,
  buy: 14,
  purchase: 14,
  shop: 14,
  store: 14,
  distributor: 14,
  distribution: 31,
  wholesale: 31,
  reseller: 31,
  resellers: 31,
  b2b: 31,
  mission: 24,
  environment: 25,
  help: 25,
  nordic: 54,
  tagline: 53,
  refreshing: 53,
  planet: 57,
  2030: 55,
  goal: 55,
  factory: 56,
  factories: 56,
  audits: 56,
  audit: 56,
  waste: 57,
  prevention: 57,
  generation: 59,
  generations: 59,
  future: 59,
  ocean: 58,
  protection: 58,
  pollution: 58,
  marine: 58,
  cleanup: 58,
  active: 60,
  lifestyle: 60,
  adventure: 60,
  coastline: 61,
  coastlines: 61,
  tradition: 62,
  traditions: 62,
  norwegian: 62,
  norway: 62,
  harmony: 62,
  nature: 62,
  health: 56,
  safety: 56,
  ethics: 52,
  ethical: 52,
  dignity: 52,
  standards: 52,
  consumption: 49,
  responsible: 49,
  production: 49,
  sdg: 48,
  goals: 48,
  careless: 46,
  care: 46,
  slogan: 47,
  innovation: 54,
  innovative: 54,
  water: 10,
  waters: 10,
  boxedwater: 10,
  waterbox: 10,
  box: 10,
  boxes: 10,
  boxed: 10,
  canned: 10,
  cannedwater: 10,
  watercan: 10,
  canister: 10,
  canisters: 10,
  aluminum: 40,
  'boxed water': 10,
  'water box': 10,
  'water can': 10,
  'canned water': 10,
  recyclable: 41,
  recycle: 41,
  recycling: 41,
  cool: 44,
  pledge: 39,
  impact: 42,
  our: 42,
  growing: 42,
  affiliate: 50,
  ambassador: 50,
  partner: 54,
  partnership: 54,
  partnerships: 56,
  partners: 54,
  collaborate: 51,
  collaboration: 51,
  collaborations: 51,
  collab: 51,
  collabs: 51,
  colab: 51,
  colabs: 51,
  collaborator: 51,
  collaborators: 51,
  teaming: 51,
  teamup: 51,
  teamingup: 51,
  work: 51,
  working: 51,
  together: 51,
  joint: 51,
  jointventure: 51,
  venture: 51,
  ventures: 51,
  sponsorship: 51,
  sponsor: 51,
  sponsorships: 51,
  sponsoring: 51,
  taiwan: 79,
  vietnam: 80,
  singapore: 80,
  asia: 80,
  dubai: 81,
  uae: 81,
  middleeast: 81,
  uk: 82,
  france: 82,
  allregions: 83,
  alldistributors: 83,
  regionlist: 83,
  distributorlist: 83,
  licensing: 52,
  liscensing: 52,
  licensee: 52,
  license: 52,
  licensed: 52,
  rblic: 53,
  rights: 53,
  brands: 53,
  brand: 53,
  branding: 53,
  branded: 53,
  rebrand: 53,
  rebranding: 53,
  caring: 46,
  cares: 46,
  cared: 46,
  recycled: 41,
  recycler: 41,
  recyclers: 41,
  supports: 34,
  supporting: 34,
  supported: 34,
  supporter: 34,
  supporters: 34,
  services: 34,
  helps: 25,
  helping: 25,
  helped: 25,
  helper: 25,
  helpers: 25,
  produce: 10,
  produced: 10,
  producing: 10,
  producer: 10,
  producers: 10,
  cleaning: 58,
  cleaned: 58,
  cleaner: 58,
  cleaners: 58,
  distributes: 31,
  distributing: 31,
  developer: 84,
  developed: 84,
  developing: 84,
  designer: 84,
  designed: 84,
  designing: 84,
  webpage: 84,
  webdesign: 84,
  webdeveloper: 84,
  webdesigner: 84,
  created: 84,
  creator: 84,
  creators: 84,
  made: 84,
  marketed: 85,
  marketer: 85,
  marketers: 85,
  socialmediamarketing: 85,
  socialmediamanagement: 85,
  creative: 86,
  creativeness: 86,
  creatively: 86,
  creativity: 86,
  artist: 86,
  artistry: 86,
  danny: 84,
  "danny nguyen": 84,
  "danny le": 84,
  dvnny: 84,
  ai: 87,
  artificial: 87,
  intelligence: 87,
  bot: 87,
  robot: 87,
  human: 88,
};

export const REGIONAL_KEYWORDS: Record<string, number | string> = {
  taiwan: 79,
  vietnam: 80,
  singapore: 80,
  dubai: 81,
  uae: 81,
  middleeast: 81,
  uk: 82,
  france: 82,
  asia: 80,
  distributors: 83,
  regions: 83,
  "all": 83,
};

export const GREETINGS: Record<string, string> = {
  hello: "Hi there! Welcome to PureNorway. How can I help you today?",
  hii: "Hi there! Welcome to PureNorway. How can I help you today?",
  hiii: "Hi there! Welcome to PureNorway. How can I help you today?",
  hi: "Hello! What would you like to know about PureNorway Water?",
  hey: "Hey! Feel free to ask me anything about our products or company.",
  heyy: "Hey! Feel free to ask me anything about our products or company.",
  heyyy: "Hey! Feel free to ask me anything about our products or company.",
  hei: "Hei! What would you like to know about PureNorway?",
  hellu: "Hi there! Welcome to PureNorway. How can I help you today?",
  helloooo: "Hi there! Welcome to PureNorway. How can I help you today?",
  yo: "Yo! What can I help you with today?",
  yoyo: "Yo! What can I help you with today?",
  sup: "Hey! What would you like to know about PureNorway?",
  wassup: "Hey! What would you like to know about PureNorway?",
  "what's up": "Hey! What would you like to know about PureNorway?",
  "whats up": "Hey! What would you like to know about PureNorway?",
  howdy: "Howdy! How can I help with PureNorway today?",
  greetings: "Greetings! Ask me anything about products, sustainability, or contact details.",
  welcome: "Welcome! Ask me anything about PureNorway.",
  morning: "Good morning! How can I help you today?",
  "good morning": "Good morning! How can I help you today?",
  afternoon: "Good afternoon! How can I help you today?",
  "good afternoon": "Good afternoon! How can I help you today?",
  evening: "Good evening! How can I help you today?",
  "good evening": "Good evening! How can I help you today?",
  "how are you": "I'm doing great, thanks for asking! How can I assist you?",
  "how are you?": "I'm doing great, thanks for asking! How can I assist you?",
  "how r u": "I'm doing great, thanks for asking! How can I assist you?",
  "how ru": "I'm doing great, thanks for asking! How can I assist you?",
  "how you doing": "I'm doing great, thanks for asking! How can I assist you?",
  "how's it going": "I'm doing great, thanks for asking! How can I assist you?",
  "hows it going": "I'm doing great, thanks for asking! How can I assist you?",
  goodbye: "Goodbye! Thanks for chatting with PureNorway. Have a great day!",
  bye: "Bye! Feel free to reach out anytime.",
  byebye: "Bye! Feel free to reach out anytime.",
  cya: "See you later! Thanks for your interest in PureNorway.",
  "see ya": "See you later! Thanks for your interest in PureNorway.",
  "talk later": "Sure, talk later. I will be here when you are back.",
  "catch you later": "Sure, talk later. I will be here when you are back.",
  "have a nice day": "Thanks! You too. Reach out anytime.",
  "see you": "See you later! Thanks for your interest in PureNorway.",
  thanks: "You're welcome! Is there anything else you'd like to know?",
  "thank you": "You're welcome! Is there anything else you'd like to know?",
  thankyou: "You're welcome! Is there anything else you'd like to know?",
  thx: "You're welcome! Is there anything else you'd like to know?",
  ty: "You're welcome! Is there anything else you'd like to know?",
  "thanks!": "You're welcome! Is there anything else you'd like to know?",
  "thank u": "You're welcome! Is there anything else you'd like to know?",
  appreciated: "Happy to help. Anything else you want to check?",
};

export const HQ_KEYWORDS = ["hq", "headquarters", "main", "office", "norway", "kristiansand", "head"];

export const CONTACT_FILTER_TERMS = [
  "contact",
  "email",
  "mail",
  "phone",
  "call",
  "support",
  "reach",
  "helpdesk",
];

export const SOCIAL_FILTER_TERMS = [
  "social",
  "socials",
  "social media",
  "instagram",
  "facebook",
  "linkedin",
  "snapchat",
  "tiktok",
  "twitter",
  "x",
];

export const PARTNERSHIP_FILTER_TERMS = [
  "partner",
  "partnership",
  "affiliate",
  "ambassador",
  "licensing",
  "license",
  "collab",
  "collaboration",
];

export const NORWAY_FILTER_TERMS = [
  "norway",
  "norge",
  "norwegian",
];

export const CONTACT_FORM_TERMS = [
  "contact form",
  "contactform",
  "form",
  "enquiry form",
  "inquiry form",
  "message form",
];

export const CREDITS_FILTER_TERMS = [
  "developed",
  "designer",
  "designed",
  "developer",
  "website",
  "marketing",
  "creative",
  "danny",
  "who made",
  "who created",
  "who built",
  "who designed",
  "who developed",
  "author",
  "author",
  "made by",
  "designed by",
  "developed by",
  "built by",
  "created by",
];

export const DIRECT_CREDITS_KEYWORDS: Record<string, number> = {
  marketing: 85,
  marketed: 85,
  marketer: 85,
  socialmedia: 85,
  socialmediamarketing: 85,
  design: 86,
  designer: 86,
  designed: 86,
  website: 86,
  webdesigner: 86,
};

// Normalize short/informal text to improve intent matching.
export const TEXT_NORMALIZATION_RULES: Array<[RegExp, string]> = [
  [/\bu\b/g, "you"],
  [/\bur\b/g, "your"],
  [/\br\b/g, "are"],
  [/\bw\//g, "with"],
  [/\bbtw\b/g, "by the way"],
  [/\bimo\b/g, "in my opinion"],
  [/\bimho\b/g, "in my humble opinion"],
  [/\bpls\b/g, "please"],
  [/\bplz\b/g, "please"],
  [/\bthx\b/g, "thanks"],
  [/\bty\b/g, "thank you"],
  [/\bnp\b/g, "no problem"],
  [/\bidk\b/g, "i do not know"],
  [/\bafaik\b/g, "as far as i know"],
  [/\bfyi\b/g, "for your information"],
  [/\bomg\b/g, "oh my god"],
  [/\bwyd\b/g, "what are you doing"],
  [/\btbh\b/g, "to be honest"],
  [/\bngl\b/g, "not gonna lie"],
  [/\bikr\b/g, "i know right"],
  [/\bfr\b/g, "for real"],
  [/\bfrfr\b/g, "for real"],
  [/\bsmh\b/g, "shaking my head"],
  [/\bttyl\b/g, "talk to you later"],
  [/\bcya\b/g, "see you"],
  [/\bgn\b/g, "good night"],
  [/\bgm\b/g, "good morning"],
  [/\bmsg\b/g, "message"],
  [/\bdm\b/g, "direct message"],
  [/\bcuz\b/g, "because"],
  [/\bcoz\b/g, "because"],
  [/\btho\b/g, "though"],
];

// Content filter to detect and censor offensive language
export const CONTENT_FILTER_PATTERNS: RegExp[] = [
  // Slurs and hate speech (case-insensitive, word boundaries where applicable)
  /\bn+\s*i+\s*g+\s*g+\s*a+\b/gi, // n-word variants
  /\bn+\s*i+\s*g+\s*e+\b/gi, // n-word alternate
  /\br+\s*e+\s*t+\s*a+\s*r+\b/gi, // r-word
  /\bf+\s*a+\s*g+\b/gi, // slur
  /\btr+\s*a+\s*n+\s*n+\s*y+\b/gi, // slur
  
  // Common cursing/profanity
  /\bf(?:u|ck)*ck\b/gi, // fuck
  /\bf\*+ck\b/gi, // f***ck variations
  /\bfucking?\b/gi, // fucking/fucked
  /\bf\*+\*+ing?\b/gi, // f***ing
  /\ba+\s*s+\s*s+\b/gi,
  /\bass(?:hole)?\b/gi,
  /\bb+\s*i+\s*tch\b/gi,
  /\bbitch(?:es)?\b/gi,
  /\bd+\s*a+\s*m+\s*n+\b/gi,
  /\bdamn(?:it)?\b/gi,
  /\bh+\s*e+\s*ll+\b/gi,
  /\bhell(?:o)?\b/gi,
  /\bp+\s*o+\s*o+\s*p+\b/gi,
  /\bpoop\b/gi,
  /\bcrap\b/gi,
  /\bshit+(?:ty|hole)?\b/gi,
  /\bbastard\b/gi,
  /\bc+\s*u+\s*n+\s*t\b/gi,
  /\bcunt\b/gi,
  /\bd+\s*i+\s*c+\s*k+\b/gi,
  /\bdick\b/gi,
  /\bp+\s*u+\s*ss+\b/gi,
  /\bpussy\b/gi,
  /\bcock\b/gi,
  /\bgodda*m+(?:n|it)?\b/gi,
];

// Helper function to check if a term matches with proper word boundaries
export const matchesTermWithBoundary = (text: string, term: string): boolean => {
  const escapedTerm = term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const pattern = new RegExp(`(^|\\s)${escapedTerm}(\\s|$)`, 'i');
  return pattern.test(text);
};

// Helper function to detect if input contains offensive language
export const containsOffensiveLanguage = (text: string): boolean => {
  return CONTENT_FILTER_PATTERNS.some(pattern => pattern.test(text));
};

// Lightweight casual chat responses for non-information utterances.
export const CASUAL_SHORTCUT_RESPONSES: Record<string, string> = {
  lol: "Glad that landed well. Want product, contact, socials, or partnership info?",
  lmao: "Happy to help. Ask me anything about products, sustainability, socials, or contact.",
  rofl: "Love the energy. Want products, contact, socials, or partnership details?",
  haha: "Nice. What do you want to check next?",
  hehe: "Nice. What do you want to check next?",
  brb: "No problem, I will be here when you are back.",
  afk: "All good. Message me when you are ready.",
  ttyl: "Sounds good. Talk soon.",
  cya: "See you later. I will be here when you are back.",
  gn: "Good night. Reach out anytime.",
  gm: "Good morning. How can I help today?",
  btw: "By the way noted. What would you like to know next?",
  idk: "No worries. I can help you narrow it down: products, contact, socials, or partnerships.",
  np: "No problem. Want to check products, contact, socials, or partnerships?",
  nvm: "No worries. If you change your mind, I can help anytime.",
  jk: "All good. What do you want help with?",
  fyi: "Thanks for the heads-up. What should we check next?",
  sup: "Hey! What can I help with today?",
  yo: "Hey! Ask me anything about PureNorway.",
  bro: "I got you. What info do you need?",
  bruh: "I got you. What info do you need?",
  "what's up": "Hey! Ask me anything about PureNorway.",
  "whats up": "Hey! Ask me anything about PureNorway.",
  kk: "Great. What would you like to check next?",
  ok: "Perfect. Tell me what you want to find.",
  okay: "Perfect. Tell me what you want to find.",
};
